[
{"keyword": "Feature", "name": "Login functionality", "tags": [], "location": "features/prueba.feature:1", "status": "failed", "elements": [{"type": "scenario", "keyword": "Scenario", "name": "Successful login with valid credentials", "tags": [], "location": "features/prueba.feature:3", "steps": [{"keyword": "Given", "step_type": "given", "name": "I am on the login page", "location": "features/prueba.feature:4", "match": {"location": "steps/login_steps.py:19", "arguments": []}, "result": {"status": "passed", "duration": 2.281834363937378}}, {"keyword": "When", "step_type": "when", "name": "I enter a valid username and password", "location": "features/prueba.feature:5", "match": {"location": "steps/login_steps.py:25", "arguments": []}, "result": {"status": "passed", "duration": 0.4903287887573242}}, {"keyword": "And", "step_type": "when", "name": "I click the login button", "location": "features/prueba.feature:6", "match": {"location": "steps/login_steps.py:35", "arguments": []}, "result": {"status": "passed", "duration": 0.8628020286560059}}, {"keyword": "Then", "step_type": "then", "name": "I should be redirected to the dashboard", "location": "features/prueba.feature:7", "match": {"location": "steps/login_steps.py:40", "arguments": []}, "result": {"status": "failed", "duration": 0.18513989448547363, "error_message": ["Traceback (most recent call last):", "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run", "    match.run(runner.context)", "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run", "    self.func(context, *args, **kwargs)", "  File \"steps\\login_steps.py\", line 48, in step_impl", "    assert context.driver.current_url == \"example.com/dashboard\"  # Cambia esto por la URL real", "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "AssertionError", "", "Captured stdout:", "https://example.com/dashboard"]}}], "status": "failed"}, {"type": "scenario", "keyword": "Scenario", "name": "Failed login with invalid credentials", "tags": [], "location": "features/prueba.feature:9", "steps": [{"keyword": "Given", "step_type": "given", "name": "I am on the login page", "location": "features/prueba.feature:10", "match": {"location": "steps/login_steps.py:19", "arguments": []}, "result": {"status": "passed", "duration": 2.2116127014160156}}, {"keyword": "When", "step_type": "when", "name": "I enter an invalid username and password", "location": "features/prueba.feature:11", "match": {"location": "steps/login_steps.py:30", "arguments": []}, "result": {"status": "passed", "duration": 0.225264310836792}}, {"keyword": "And", "step_type": "when", "name": "I click the login button", "location": "features/prueba.feature:12", "match": {"location": "steps/login_steps.py:35", "arguments": []}, "result": {"status": "passed", "duration": 0.19193339347839355}}, {"keyword": "Then", "step_type": "then", "name": "I should see an error message", "location": "features/prueba.feature:13", "match": {"location": "steps/login_steps.py:51", "arguments": []}, "result": {"status": "passed", "duration": 2.300593376159668}}], "status": "passed"}]}
]
